parent_user = User.create!(
  name: 'Mat',
  email: 'parent@email.com',
  password: 'password',
  avatar: 'https://images.vexels.com/media/users/3/145908/preview2/52eabf633ca6414e60a7677b0b917d92-male-avatar-maker.jpg'
)

child_user = User.create!(
  name: 'Meeyu',
  email: 'meow@email.com',
  password: 'password',
  avatar: 'https://previews.123rf.com/images/lar01joka/lar01joka1806/lar01joka180600036/102460124-isolated-cute-cat-avatar.jpg'
)

parent_user = User.create!(
    name: 'Lirit',
    email: 'child@example.com',
    password: 'password',
    avatar: 'https://previews.123rf.com/images/juliasart/juliasart1704/juliasart170400022/75406270-vector-girl-icon-woman-avatar-face-icon-cartoon-style-.jpg'
)

child_user = User.create!(
  name: 'Wookie',
  email: 'meow@email.com',
  password: 'password',
  avatar: 'https://previews.123rf.com/images/alexutemov/alexutemov1608/alexutemov160800980/61881092-cute-animal-cat-head-emotion-vector-avatar-cartoon-happy-cat-kitty-animal-emotion-expression-isolate.jpg'
)

Task.create!(
  name: "Get straight A's on your Report Card",
  value: '500',
  image: 'https://i.pinimg.com/originals/e6/5d/86/e65d86af554c7faabc16684669edfa76.png',
  taskGiverId: '1',
  taskReceiverId: '4',
  stickerImage: 'https://i.pinimg.com/736x/b5/62/7b/b5627bd17db63bf4821bb14f976101e8.jpg'
)

Task.create!(
  name: 'Do the dishes',
  value: '20',
  image: 'https://c.stocksy.com/a/24x700/z9/1895342.jpg?1575844750',
  taskGiverId: '1',
  taskReceiverId: '2',
  stickerImage: 'https://i.pinimg.com/736x/b5/62/7b/b5627bd17db63bf4821bb14f976101e8.jpg'
)

Task.create!(
  name: 'Feed the animals',
  value: '5',
  image: 'https://www.theinternetpetvet.com/wp-content/uploads/2014/09/dog-cat-feeding.jpg',
  taskGiverId: '3',
  taskReceiverId: '2',
  stickerImage: 'https://i.pinimg.com/736x/b5/62/7b/b5627bd17db63bf4821bb14f976101e8.jpg'
)

TaskImage.create!([
  { imageUrl: 'https://i.imgur.com/YwvNgLZ.jpg'},
  { imageUrl: 'https://i.imgur.com/4J3fO7m.jpg'},
  { imageUrl: 'https://i.imgur.com/kClGGmM.jpg'},
  { imageUrl: 'https://i.imgur.com/Ptbvxn1.jpg'},
  { imageUrl: 'https://i.imgur.com/RzXBsuJ.jpg'},
  { imageUrl: 'https://i.imgur.com/gIbsgTQ.jpg'},
  { imageUrl: 'https://i.imgur.com/mGX2pY9.jpg'},
  { imageUrl: 'https://i.imgur.com/M4OPTLg.jpg'},
  { imageUrl: 'https://i.imgur.com/dRFXbCY.jpg'},
  { imageUrl: 'https://i.imgur.com/jxi1M4L.jpg'},
  { imageUrl: 'https://i.imgur.com/CI4KWj8.jpg'},
  { imageUrl: 'https://i.imgur.com/03IztFi.jpg'},
  { imageUrl: 'https://i.imgur.com/gL1X9Zk.jpg'},
  { imageUrl: 'https://i.imgur.com/OOQL4El.jpg'},
  { imageUrl: 'https://i.imgur.com/wNR7SqW.jpg'},
  { imageUrl: 'https://i.imgur.com/LmFeg9p.jpg'},
  { imageUrl: 'https://i.imgur.com/JjjQJcn.jpg'},
  { imageUrl: 'https://i.imgur.com/A3ouTpS.jpg'},
  { imageUrl: 'https://i.imgur.com/sZXMwX1.jpg'},
  { imageUrl: 'https://i.imgur.com/GbRreTD.jpg'},
  { imageUrl: 'https://i.imgur.com/8WbeGQf.jpg'},
  { imageUrl: 'https://i.imgur.com/GmT4jVa.jpg'},
  { imageUrl: 'https://i.imgur.com/gTWbUhP.jpg'},
  { imageUrl: 'https://i.imgur.com/oSFlAOI.jpg'},
  { imageUrl: 'https://i.imgur.com/S8qK2Vd.jpg'},
  { imageUrl: 'https://i.imgur.com/INRruvl.jpg'},
  { imageUrl: 'https://i.imgur.com/qg7I005.jpg'},
  { imageUrl: 'https://i.imgur.com/VuS43yO.jpg'},
  { imageUrl: 'https://i.imgur.com/fIsn7yz.jpg'},
  { imageUrl: 'https://i.imgur.com/ERK7ioC.jpg'},
  { imageUrl: 'https://i.imgur.com/xlYUXTv.jpg'},
  { imageUrl: 'https://i.imgur.com/uVWMy6l.jpg'},
  { imageUrl: 'https://i.imgur.com/jqKcqCm.jpg'},
  { imageUrl: 'https://i.imgur.com/ThLfjFd.jpg'},
  { imageUrl: 'https://i.imgur.com/lhyDX2d.jpg'},
  { imageUrl: 'https://i.imgur.com/HT8v06Y.jpg'},
  { imageUrl: 'https://i.imgur.com/bY9hW2h.jpg'},
  { imageUrl: 'https://i.imgur.com/s55fuw7.jpg'},
  { imageUrl: 'https://i.imgur.com/0i07oWz.jpg'},
  { imageUrl: 'https://i.imgur.com/0IcO6Nt.jpg'},
  { imageUrl: 'https://i.imgur.com/Lx3724F.jpg'},
  { imageUrl: 'https://i.imgur.com/PGBpYWc.jpg'},
  { imageUrl: 'https://i.imgur.com/YgBAzQ2.jpg'},
  { imageUrl: 'https://i.imgur.com/zYqS7Hj.jpg'},
  { imageUrl: 'https://i.imgur.com/VUa769Y.jpg'},
  { imageUrl: 'https://i.imgur.com/oQmBAj6.jpg'},
  { imageUrl: 'https://i.imgur.com/Wk6lTv6.jpg'},
  { imageUrl: 'https://i.imgur.com/DwhCYmU.jpg'},
  { imageUrl: 'https://i.imgur.com/9Kmh5u1.jpg'},
  { imageUrl: 'https://i.imgur.com/bnCRO47.jpg'},
  { imageUrl: 'https://i.imgur.com/iklSH0X.jpg'},
  { imageUrl: 'https://i.imgur.com/QfWtRQ7.jpg'},
  { imageUrl: 'https://i.imgur.com/dFvIEnk.jpg'},
  { imageUrl: 'https://i.imgur.com/z5nSfR8.jpg'},
  { imageUrl: 'https://i.imgur.com/WE8T2Xk.jpg'},
  { imageUrl: 'https://i.imgur.com/5Z9QLUi.jpg'},
  { imageUrl: 'https://i.imgur.com/QZ7slEN.jpg'},
  { imageUrl: 'https://i.imgur.com/WtWlTkN.jpg'},
  { imageUrl: 'https://i.imgur.com/LElv3V6.jpg'},
  { imageUrl: 'https://i.imgur.com/cngdO04.jpg'},
  { imageUrl: 'https://i.imgur.com/puX3TtY.jpg'},
  { imageUrl: 'https://i.imgur.com/VmALA61.jpg'},
  { imageUrl: 'https://i.imgur.com/myqIsWL.jpg'},
  { imageUrl: 'https://i.imgur.com/jdfqovj.jpg'},
  { imageUrl: 'https://i.imgur.com/AIz2WpM.jpg'},
  { imageUrl: 'https://i.imgur.com/AcnbjyW.jpg'},
  { imageUrl: 'https://i.imgur.com/ZjuvdSr.jpg'},
  { imageUrl: 'https://i.imgur.com/BDmAgCX.jpg'},
  { imageUrl: 'https://i.imgur.com/quBv251.jpg'},
  { imageUrl: 'https://i.imgur.com/sjYRz53.jpg'},
  { imageUrl: 'https://i.imgur.com/HmZdxsE.jpg'},
  { imageUrl: 'https://i.imgur.com/tKjNNon.jpg'},
  { imageUrl: 'https://i.imgur.com/7lX9bAD.jpg'},
  { imageUrl: 'https://i.imgur.com/X0L3GoZ.jpg'},
  { imageUrl: 'https://i.imgur.com/7XpC2yT.jpg'},
  { imageUrl: 'https://i.imgur.com/yFrNaGU.jpg'},
  { imageUrl: 'https://i.imgur.com/ZSO6Azd.jpg'},
  { imageUrl: 'https://i.imgur.com/itfGIv9.jpg'},
  { imageUrl: 'https://i.imgur.com/p3QcbDT.jpg'},
  { imageUrl: 'https://i.imgur.com/rv1hMwU.jpg'},
  { imageUrl: 'https://i.imgur.com/1Ge4dqW.jpg'},
  { imageUrl: 'https://i.imgur.com/QSb7LZh.jpg'},
  { imageUrl: 'https://i.imgur.com/q8j4oyX.jpg'},
  { imageUrl: 'https://i.imgur.com/0u79aTG.jpg'},
  { imageUrl: 'https://i.imgur.com/OAzNzFl.jpg'},
  { imageUrl: 'https://i.imgur.com/A8oJSXu.jpg'},
  { imageUrl: 'https://i.imgur.com/zZwIqpl.jpg'},
  { imageUrl: 'https://i.imgur.com/vZwDRpS.jpg'},
  { imageUrl: 'https://i.imgur.com/U4Ny13p.jpg'},
  { imageUrl: 'https://i.imgur.com/IhmUEaQ.jpg'},
  { imageUrl: 'https://i.imgur.com/GIozw0m.jpg'},
  { imageUrl: 'https://i.imgur.com/wQxHmcE.jpg'},
  { imageUrl: 'https://i.imgur.com/v5FeCgh.jpg'},
  { imageUrl: 'https://i.imgur.com/zv8t2wz.jpg'},
  { imageUrl: 'https://i.imgur.com/yI7JPlj.jpg'},
  { imageUrl: 'https://i.imgur.com/xhqr6Vl.jpg'},
  { imageUrl: 'https://i.imgur.com/jidYfLy.jpg'},
  { imageUrl: 'https://i.imgur.com/h9drnXA.jpg'},
  { imageUrl: 'https://i.imgur.com/0kZOuEy.jpg'},
  { imageUrl: 'https://i.imgur.com/S5zQCs6.jpg'},
  { imageUrl: 'https://i.imgur.com/cilLjDc.jpg'},
  { imageUrl: 'https://i.imgur.com/3d85k6b.jpg'},
  { imageUrl: 'https://i.imgur.com/3VfUsuV.jpg'},
  { imageUrl: 'https://i.imgur.com/qvcMRpb.jpg'},
  { imageUrl: 'https://i.imgur.com/slqoAiy.jpg'},
  { imageUrl: 'https://i.imgur.com/4U5HMsm.jpg'},
  { imageUrl: 'https://i.imgur.com/rob0CvE.jpg'},
  { imageUrl: 'https://i.imgur.com/F1mmSFY.jpg'},
  { imageUrl: 'https://i.imgur.com/TI6Sd9I.jpg'},
  { imageUrl: 'https://i.imgur.com/dZfdq9z.jpg'},
  { imageUrl: 'https://i.imgur.com/Eqow8b5.jpg'},
  { imageUrl: 'https://i.imgur.com/rpnOh83.jpg'},
  { imageUrl: 'https://i.imgur.com/ErTTAUQ.jpg'},
  { imageUrl: 'https://i.imgur.com/sylpQac.jpg'},
  { imageUrl: 'https://i.imgur.com/W19JB9r.jpg'},
  { imageUrl: 'https://i.imgur.com/dW98ceB.jpg'},
  { imageUrl: 'https://i.imgur.com/Dirp1BC.jpg'},
  { imageUrl: 'https://i.imgur.com/l7VQ8DV.jpg'},
  { imageUrl: 'https://i.imgur.com/D4BHO7D.jpg'},
  { imageUrl: 'https://i.imgur.com/FjBZcJs.jpg'},
  { imageUrl: 'https://i.imgur.com/X1ynVZn.jpg'},
  { imageUrl: 'https://i.imgur.com/IoZya8c.jpg'},
  { imageUrl: 'https://i.imgur.com/AFa8w2Q.jpg'},
  { imageUrl: 'https://i.imgur.com/ll9VtBZ.jpg'},
  { imageUrl: 'https://i.imgur.com/8nb8N9V.jpg'},
  { imageUrl: 'https://i.imgur.com/DiSdMSK.jpg'},
  { imageUrl: 'https://i.imgur.com/d9TPY1h.jpg'},
  { imageUrl: 'https://i.imgur.com/3tFNvfa.jpg'},
  { imageUrl: 'https://i.imgur.com/CYWIxj7.jpg'},
  { imageUrl: 'https://i.imgur.com/aqj35UN.jpg'},
  { imageUrl: 'https://i.imgur.com/foWhMlb.jpg'},
  { imageUrl: 'https://i.imgur.com/etKf4xx.jpg'},
  { imageUrl: 'https://i.imgur.com/21O7NCz.jpg'},
  { imageUrl: 'https://i.imgur.com/rSVblhM.jpg'},
  { imageUrl: 'https://i.imgur.com/grzIXNS.jpg'},
  { imageUrl: 'https://i.imgur.com/M8R6k5M.jpg'},
  { imageUrl: 'https://i.imgur.com/mDXg1WK.jpg'},
  { imageUrl: 'https://i.imgur.com/0vJG2JQ.jpg'},
  { imageUrl: 'https://i.imgur.com/ovPIiCA.jpg'},
  { imageUrl: 'https://i.imgur.com/YEho3BH.jpg'},
  { imageUrl: 'https://i.imgur.com/STmNmJd.jpg'},
  { imageUrl: 'https://i.imgur.com/xOUvnWu.jpg'},
  { imageUrl: 'https://i.imgur.com/ZpLRAsT.jpg'},
  { imageUrl: 'https://i.imgur.com/XdIgN9u.jpg'},
  { imageUrl: 'https://i.imgur.com/ESxsXzV.jpg'},
  { imageUrl: 'https://i.imgur.com/Nxo3rk8.jpg'},
  { imageUrl: 'https://i.imgur.com/F7aOuHT.jpg'},
  { imageUrl: 'https://i.imgur.com/eYg02l4.jpg'},
  { imageUrl: 'https://i.imgur.com/Axi2cci.jpg'},
  { imageUrl: 'https://i.imgur.com/dyIUxbq.jpg'},
  { imageUrl: 'https://i.imgur.com/UXcLP3H.jpg'},
  { imageUrl: 'https://i.imgur.com/8sIUUSA.jpg'},
  { imageUrl: 'https://i.imgur.com/ZJ5rAkc.jpg'},
  { imageUrl: 'https://i.imgur.com/A4Yidzj.jpg'},
  { imageUrl: 'https://i.imgur.com/gi0jduW.jpg'},
  { imageUrl: 'https://i.imgur.com/66wbjEW.jpg'},
  { imageUrl: 'https://i.imgur.com/EsIVPXp.jpg'},
  { imageUrl: 'https://i.imgur.com/qrjtTJK.jpg'},
  { imageUrl: 'https://i.imgur.com/8xWITXd.jpg'},
  { imageUrl: 'https://i.imgur.com/g5sZPkp.jpg'}])

#{ imageUrl: ''}


Sticker.create!([
  { image: 'https://i.imgur.com/VEt4BPW.png'},
  { image: 'https://i.imgur.com/z9orHTZ.jpg'},
  { image: 'https://i.imgur.com/RXaSo3M.jpg'},
  { image: 'https://i.imgur.com/skX6Uva.jpg'},
  { image: 'https://i.imgur.com/9kkMSRY.jpg'},
  { image: 'https://i.imgur.com/C2Gk2Kt.jpg'},
  { image: 'https://i.imgur.com/47xwoWo.jpg'},
  { image: 'https://i.imgur.com/Butgl1M.jpg'},
  { image: 'https://i.imgur.com/HTDfO1t.jpg'},
  { image: 'https://i.imgur.com/F19TaaK.jpg'},
  { image: 'https://i.imgur.com/5UlUkdw.jpg'},
  { image: 'https://i.imgur.com/2qrHvBY.jpg'},
  { image: 'https://i.imgur.com/tkiaszT.jpg'},
  { image: 'https://i.imgur.com/eHD2yhC.jpg'},
  { image: 'https://i.imgur.com/qNFeOXm.jpg'},
  { image: 'https://i.imgur.com/WdeoeAe.jpg'},
  { image: 'https://i.imgur.com/s0Px7VY.jpg'},
  { image: 'https://i.imgur.com/eFNkDMg.jpg'},
  { image: 'https://i.imgur.com/ipwZe5v.jpg'},
  { image: 'https://i.imgur.com/jzaaEJK.jpg'},
  { image: 'https://i.imgur.com/juFzo0y.jpg'},
  { image: 'https://i.imgur.com/v7jVukw.jpg'},
  { image: 'https://i.imgur.com/YapnA0l.jpg'},
  { image: 'https://i.imgur.com/amCwJMK.jpg'},
  { image: 'https://i.imgur.com/ZsTB3Xi.jpg'},
  { image: 'https://i.imgur.com/jkJ5BnP.jpg'},
  { image: 'https://i.imgur.com/OnymgqA.jpg'},
  { image: 'https://i.imgur.com/8XbxtCz.jpg'},
  { image: 'https://i.imgur.com/M7FsIIg.jpg'},
  { image: 'https://i.imgur.com/7QjGLyc.jpg'},
  { image: 'https://i.imgur.com/tfmarmU.jpg'},
  { image: 'https://i.imgur.com/kTfs18G.jpg'},
  { image: 'https://i.imgur.com/fGJw28b.jpg'},
  { image: 'https://i.imgur.com/2zjRMJF.jpg'},
  { image: 'https://i.imgur.com/vpAwuWy.jpg'},
  { image: 'https://i.imgur.com/4MXHFDo.jpg'},
  { image: 'https://i.imgur.com/jyHtvOC.jpg'},
  { image: 'https://i.imgur.com/ugoOtfz.jpg'},
  { image: 'https://i.imgur.com/vf1QZ1d.jpg'},
  { image: 'https://i.imgur.com/84Wm7WL.jpg'},
  { image: 'https://i.imgur.com/2CoY7Wa.jpg'},
  { image: 'https://i.imgur.com/TOXo2w6.jpg'},
  { image: 'https://i.imgur.com/ZjnicsV.jpg'},
  { image: 'https://i.imgur.com/ur5x2xx.jpg'},
  { image: 'https://i.imgur.com/cOFSbqG.jpg'},
  { image: 'https://i.imgur.com/2UBsFzu.jpg'},
  { image: 'https://i.imgur.com/hk8XTwP.jpg'},
  { image: 'https://i.imgur.com/4lTKJn2.jpg'},
  { image: 'https://i.imgur.com/vbkeTW5.jpg'},
  { image: 'https://i.imgur.com/J3jAWcu.jpg'},
  { image: 'https://i.imgur.com/VqKDiQL.jpg'},
  { image: 'https://i.imgur.com/M6JmheH.jpg'},
  { image: 'https://i.imgur.com/oCQSo0r.jpg'},
  { image: 'https://i.imgur.com/FxhKNob.jpg'},
  { image: 'https://i.imgur.com/QzATUnS.jpg'},
  { image: 'https://i.imgur.com/ELtcoe8.jpg'},
  { image: 'https://i.imgur.com/vNECm8m.jpg'},
  { image: 'https://i.imgur.com/LiEUGmA.jpg'},
  { image: 'https://i.imgur.com/0QFvJxa.jpg'},
  { image: 'https://i.imgur.com/PPYyVXb.jpg'},
  { image: 'https://i.imgur.com/9WYRahz.jpg'},
  { image: 'https://i.imgur.com/5MOIwWu.jpg'},
  { image: 'https://i.imgur.com/0LkJwXa.jpg'},
  { image: 'https://i.imgur.com/yEksjav.jpg'},
  { image: 'https://i.imgur.com/XXE1R9v.jpg'},
  { image: 'https://i.imgur.com/Qer2SLH.jpg'},
  { image: 'https://i.imgur.com/3LRFE3H.jpg'},
  { image: 'https://i.imgur.com/N6shLKc.jpg'},
  { image: 'https://i.imgur.com/FgX2lU9.jpg'},
  { image: 'https://i.imgur.com/SzRdOnh.jpg'},
  { image: 'https://i.imgur.com/Xv5bvWN.jpg'},
  { image: 'https://i.imgur.com/ZLaokRL.jpg'},
  { image: 'https://i.imgur.com/SbzJWys.jpg'},
  { image: 'https://i.imgur.com/QNlRHuY.jpg'},
  { image: 'https://i.imgur.com/QraxwTz.jpg'},
  { image: 'https://i.imgur.com/dAJLvcH.jpg'},
  { image: 'https://i.imgur.com/I560y6F.jpg'},
  { image: 'https://i.imgur.com/lsHe9WU.jpg'},
  { image: 'https://i.imgur.com/9FbIu2z.jpg'},
  { image: 'https://i.imgur.com/CPNn2hy.jpg'},
  { image: 'https://i.imgur.com/cts5CDk.jpg'},
  { image: 'https://i.imgur.com/HyaQo4D.jpg'},
  { image: 'https://i.imgur.com/VrBCVqS.jpg'},
  { image: 'https://i.imgur.com/tyEi2xC.jpg'},
  { image: 'https://i.imgur.com/Uu4uRwY.jpg'},
  { image: 'https://i.imgur.com/3Q5SOYM.jpg'},
  { image: 'https://i.imgur.com/6wyEKOp.jpg'},
  { image: 'https://i.imgur.com/tMP7PYE.jpg'},
  { image: 'https://i.imgur.com/G8FLtkw.jpg'},
  { image: 'https://i.imgur.com/EScvig7.jpg'},
  { image: 'https://i.imgur.com/xwzJNR0.jpg'},
  { image: 'https://i.imgur.com/K3L7G7X.jpg'},
  { image: 'https://i.imgur.com/HK0hexr.jpg'},
  { image: 'https://i.imgur.com/B3nNhLZ.jpg'},
  { image: 'https://i.imgur.com/pXVzS6o.jpg'},
  { image: 'https://i.imgur.com/zOEa8PW.jpg'},
  { image: 'https://i.imgur.com/wjMA4qa.jpg'},
  { image: 'https://i.imgur.com/dIl7Itf.jpg'},
  { image: 'https://i.imgur.com/PXcyvHm.jpg'},
  { image: 'https://i.imgur.com/s9u2hXK.jpg'},
  { image: 'https://i.imgur.com/Fyxo5ON.jpg'},
  { image: 'https://i.imgur.com/Mf1JixN.jpg'},
  { image: 'https://i.imgur.com/Mdacm1F.jpg'},
  { image: 'https://i.imgur.com/ZChUUu0.jpg'},
  { image: 'https://i.imgur.com/noZfsDe.jpg'},
  { image: 'https://i.imgur.com/rJNxztU.jpg'},
  { image: 'https://i.imgur.com/xqGUpvh.jpg'},
  { image: 'https://i.imgur.com/7BRB3ff.jpg'},
  { image: 'https://i.imgur.com/hhLOl7b.jpg'},
  { image: 'https://i.imgur.com/CMs5amJ.jpg'},
  { image: 'https://i.imgur.com/LITg6KT.jpg'},
  { image: 'https://i.imgur.com/kAuPQze.jpg'},
  { image: 'https://i.imgur.com/QhNxtwI.jpg'},
  { image: 'https://i.imgur.com/BGuLtfY.jpg'},
  { image: 'https://i.imgur.com/xTPPcFc.jpg'},
  { image: 'https://i.imgur.com/CZfhctY.jpg'},
  { image: 'https://i.imgur.com/lXrGiKQ.jpg'},
  { image: 'https://i.imgur.com/s4sxMA9.jpg'},
  { image: 'https://i.imgur.com/ofWEjib.jpg'},
  { image: 'https://i.imgur.com/VfLj14v.jpg'},
  { image: 'https://i.imgur.com/Dgkt9lw.jpg'},
  { image: 'https://i.imgur.com/KutIQ4i.jpg'},
  { image: 'https://i.imgur.com/kdReYTw.jpg'},
  { image: 'https://i.imgur.com/7GgEwcv.jpg'},
  { image: 'https://i.imgur.com/gsDlpLe.jpg'},
  { image: 'https://i.imgur.com/gjtPef6.jpg'},
  { image: 'https://i.imgur.com/PsFprfe.jpg'},
  { image: 'https://i.imgur.com/h8PaZlu.jpg'},
  { image: 'https://i.imgur.com/uvTEmG4.jpg'},
  { image: 'https://i.imgur.com/8vCvDrL.jpg'},
  { image: 'https://i.imgur.com/GthUuOx.jpg'},
  { image: 'https://i.imgur.com/vCUWmO8.jpg'},
  { image: 'https://i.imgur.com/iuzcv92.jpg'},
  { image: 'https://i.imgur.com/PhmrzeR.jpg'},
  { image: 'https://i.imgur.com/5g5ON9w.jpg'},
  { image: 'https://i.imgur.com/eFpCOzc.jpg'},
  { image: 'https://i.imgur.com/LdFf0Fm.jpg'},
  { image: 'https://i.imgur.com/kGPENzh.jpg'},
  { image: 'https://i.imgur.com/Us0lcvF.jpg'},
  { image: 'https://i.imgur.com/K4zAeQz.jpg'},
  { image: 'https://i.imgur.com/VcT1Kel.jpg'},
  { image: 'https://i.imgur.com/k7p8xb6.jpg'},
  { image: 'https://i.imgur.com/2bhVxg5.jpg'},
  { image: 'https://i.imgur.com/H15c3qi.jpg'},
  { image: 'https://i.imgur.com/9oa8lMJ.jpg'},
  { image: 'https://i.imgur.com/SfClgKD.jpg'},
  { image: 'https://i.imgur.com/7wsvs9B.jpg'},
  { image: 'https://i.imgur.com/O9RLaS8.jpg'},
  { image: 'https://i.imgur.com/Jfeznh3.jpg'},
  { image: 'https://i.imgur.com/n7pw59c.jpg'},
  { image: 'https://i.imgur.com/hGlj2iB.jpg'},
  { image: 'https://i.imgur.com/I0Ep5j7.jpg'},
  { image: 'https://i.imgur.com/FTT5PRA.jpg'},
  { image: 'https://i.imgur.com/9QidApE.jpg'},
  { image: 'https://i.imgur.com/2OEWMpX.jpg'},
  { image: 'https://i.imgur.com/BWAw70W.jpg'},
  { image: 'https://i.imgur.com/7cZ9VPc.jpg'},
  { image: 'https://i.imgur.com/9OdR1u3.jpg'},
  { image: 'https://i.imgur.com/3c2rX3A.jpg'},
  { image: 'https://i.imgur.com/hQgVqXV.jpg'},
  { image: 'https://i.imgur.com/dXW85aD.jpg'},
  { image: 'https://i.imgur.com/ofPu10A.jpg'},
  { image: 'https://i.imgur.com/AC4ccS3.jpg'},
  { image: 'https://i.imgur.com/DfQpE5I.jpg'},
  { image: 'https://i.imgur.com/RJrjNv0.jpg'},
  { image: 'https://i.imgur.com/lBcZbmA.png'},
  { image: 'https://i.imgur.com/JWTw3PW.jpg'},
  { image: 'https://i.imgur.com/ZCEyBLG.jpg'}])

  #{ image: ''}

system "clear"  
  puts "After seeding the database: "
  puts " - There are #{User.count} Users."
  puts " - There are #{Task.count} Tasks."
  puts " - There are #{TaskImage.count} Task Images."
  puts " - There are #{Sticker.count} Stickers."
  puts ""