parent_user = User.create!(
  name: 'Mat',
  email: 'parent@email.com',
  password: 'password',
  avatar: 'https://images.vexels.com/media/users/3/145908/preview2/52eabf633ca6414e60a7677b0b917d92-male-avatar-maker.jpg'
)

child_user = User.create!(
  name: 'Meeyu',
  email: 'meow@email.com',
  password: 'password',
  avatar: 'https://previews.123rf.com/images/lar01joka/lar01joka1806/lar01joka180600036/102460124-isolated-cute-cat-avatar.jpg'
)

parent_user = User.create!(
    name: 'Lirit',
    email: 'child@example.com',
    password: 'password',
    avatar: 'https://previews.123rf.com/images/juliasart/juliasart1704/juliasart170400022/75406270-vector-girl-icon-woman-avatar-face-icon-cartoon-style-.jpg'
)

child_user = User.create!(
  name: 'Wookie',
  email: 'meow@email.com',
  password: 'password',
  avatar: 'https://previews.123rf.com/images/alexutemov/alexutemov1608/alexutemov160800980/61881092-cute-animal-cat-head-emotion-vector-avatar-cartoon-happy-cat-kitty-animal-emotion-expression-isolate.jpg'
)

Task.create!(
  name: "Get straight A's on your Report Card",
  value: '500',
  image: 'https://i.pinimg.com/originals/e6/5d/86/e65d86af554c7faabc16684669edfa76.png',
  taskGiverId: '1',
  taskReceiverId: '4',
  stickerImage: 'https://i.pinimg.com/736x/b5/62/7b/b5627bd17db63bf4821bb14f976101e8.jpg'
)

Task.create!(
  name: 'Do the dishes',
  value: '20',
  image: 'https://c.stocksy.com/a/24x700/z9/1895342.jpg?1575844750',
  taskGiverId: '1',
  taskReceiverId: '2',
  stickerImage: 'https://i.pinimg.com/736x/b5/62/7b/b5627bd17db63bf4821bb14f976101e8.jpg'
)

Task.create!(
  name: 'Feed the animals',
  value: '5',
  image: 'https://www.theinternetpetvet.com/wp-content/uploads/2014/09/dog-cat-feeding.jpg',
  taskGiverId: '3',
  taskReceiverId: '2',
  stickerImage: 'https://i.pinimg.com/736x/b5/62/7b/b5627bd17db63bf4821bb14f976101e8.jpg'
)

TaskImage.create!(imageUrl: 'http://clipart-library.com/data_images/423864.png')


Sticker.create!([{ image: 'https://i.imgur.com/VEt4BPW.png'},
  { image: 'https://i.imgur.com/z9orHTZ.jpg'},
  { image: 'https://i.imgur.com/RXaSo3M.jpg'},
  { image: 'https://i.imgur.com/skX6Uva.jpg'},
  { image: 'https://i.imgur.com/9kkMSRY.jpg'},
  { image: 'https://i.imgur.com/C2Gk2Kt.jpg'},
  { image: 'https://i.imgur.com/47xwoWo.jpg'},
  { image: 'https://i.imgur.com/Butgl1M.jpg'},
  { image: 'https://i.imgur.com/HTDfO1t.jpg'},
  { image: 'https://i.imgur.com/F19TaaK.jpg'},
  { image: 'https://i.imgur.com/5UlUkdw.jpg'},
  { image: 'https://i.imgur.com/2qrHvBY.jpg'},
  { image: 'https://i.imgur.com/tkiaszT.jpg'},
  { image: 'https://i.imgur.com/eHD2yhC.jpg'},
  { image: 'https://i.imgur.com/qNFeOXm.jpg'},
  { image: 'https://i.imgur.com/WdeoeAe.jpg'},
  { image: 'https://i.imgur.com/s0Px7VY.jpg'},
  { image: 'https://i.imgur.com/eFNkDMg.jpg'},
  { image: 'https://i.imgur.com/ipwZe5v.jpg'},
  { image: 'https://i.imgur.com/jzaaEJK.jpg'},
  { image: 'https://i.imgur.com/juFzo0y.jpg'},
  { image: 'https://i.imgur.com/v7jVukw.jpg'},
  { image: 'https://i.imgur.com/YapnA0l.jpg'},
  { image: 'https://i.imgur.com/amCwJMK.jpg'},
  { image: 'https://i.imgur.com/ZsTB3Xi.jpg'},
  { image: 'https://i.imgur.com/jkJ5BnP.jpg'},
  { image: 'https://i.imgur.com/OnymgqA.jpg'},
  { image: 'https://i.imgur.com/8XbxtCz.jpg'},
  { image: 'https://i.imgur.com/M7FsIIg.jpg'},
  { image: 'https://i.imgur.com/7QjGLyc.jpg'},
  { image: 'https://i.imgur.com/tfmarmU.jpg'},
  { image: 'https://i.imgur.com/kTfs18G.jpg'},
  { image: 'https://i.imgur.com/fGJw28b.jpg'},
  { image: 'https://i.imgur.com/2zjRMJF.jpg'},
  { image: 'https://i.imgur.com/vpAwuWy.jpg'},
  { image: 'https://i.imgur.com/4MXHFDo.jpg'},
  { image: 'https://i.imgur.com/jyHtvOC.jpg'},
  { image: 'https://i.imgur.com/ugoOtfz.jpg'},
  { image: 'https://i.imgur.com/vf1QZ1d.jpg'},
  { image: 'https://i.imgur.com/84Wm7WL.jpg'},
  { image: 'https://i.imgur.com/2CoY7Wa.jpg'},
  { image: 'https://i.imgur.com/TOXo2w6.jpg'},
  { image: 'https://i.imgur.com/ZjnicsV.jpg'},
  { image: 'https://i.imgur.com/ur5x2xx.jpg'},
  { image: 'https://i.imgur.com/cOFSbqG.jpg'},
  { image: 'https://i.imgur.com/2UBsFzu.jpg'},
  { image: 'https://i.imgur.com/hk8XTwP.jpg'},
  { image: 'https://i.imgur.com/4lTKJn2.jpg'},
  { image: 'https://i.imgur.com/vbkeTW5.jpg'},
  { image: 'https://i.imgur.com/J3jAWcu.jpg'},
  { image: 'https://i.imgur.com/VqKDiQL.jpg'},
  { image: 'https://i.imgur.com/M6JmheH.jpg'},
  { image: 'https://i.imgur.com/oCQSo0r.jpg'},
  { image: 'https://i.imgur.com/FxhKNob.jpg'},
  { image: 'https://i.imgur.com/QzATUnS.jpg'},
  { image: 'https://i.imgur.com/ELtcoe8.jpg'},
  { image: 'https://i.imgur.com/vNECm8m.jpg'},
  { image: 'https://i.imgur.com/LiEUGmA.jpg'},
  { image: 'https://i.imgur.com/0QFvJxa.jpg'},
  { image: 'https://i.imgur.com/PPYyVXb.jpg'},
  { image: 'https://i.imgur.com/9WYRahz.jpg'},
  { image: 'https://i.imgur.com/5MOIwWu.jpg'},
  { image: 'https://i.imgur.com/0LkJwXa.jpg'},
  { image: 'https://i.imgur.com/yEksjav.jpg'},
  { image: 'https://i.imgur.com/XXE1R9v.jpg'},
  { image: 'https://i.imgur.com/Qer2SLH.jpg'},
  { image: 'https://i.imgur.com/3LRFE3H.jpg'},
  { image: 'https://i.imgur.com/N6shLKc.jpg'},
  { image: 'https://i.imgur.com/FgX2lU9.jpg'},
  { image: 'https://i.imgur.com/SzRdOnh.jpg'},
  { image: 'https://i.imgur.com/Xv5bvWN.jpg'},
  { image: 'https://i.imgur.com/ZLaokRL.jpg'},
  { image: 'https://i.imgur.com/SbzJWys.jpg'},
  { image: 'https://i.imgur.com/QNlRHuY.jpg'},
  { image: 'https://i.imgur.com/QraxwTz.jpg'},
  { image: 'https://i.imgur.com/dAJLvcH.jpg'},
  { image: 'https://i.imgur.com/I560y6F.jpg'},
  { image: 'https://i.imgur.com/lsHe9WU.jpg'},
  { image: 'https://i.imgur.com/9FbIu2z.jpg'},
  { image: 'https://i.imgur.com/CPNn2hy.jpg'},
  { image: 'https://i.imgur.com/cts5CDk.jpg'},
  { image: 'https://i.imgur.com/HyaQo4D.jpg'},
  { image: 'https://i.imgur.com/VrBCVqS.jpg'},
  { image: 'https://i.imgur.com/tyEi2xC.jpg'},
  { image: 'https://i.imgur.com/Uu4uRwY.jpg'},
  { image: 'https://i.imgur.com/3Q5SOYM.jpg'},
  { image: 'https://i.imgur.com/6wyEKOp.jpg'},
  { image: 'https://i.imgur.com/tMP7PYE.jpg'},
  { image: 'https://i.imgur.com/G8FLtkw.jpg'},
  { image: 'https://i.imgur.com/EScvig7.jpg'},
  { image: 'https://i.imgur.com/xwzJNR0.jpg'},
  { image: 'https://i.imgur.com/K3L7G7X.jpg'},
  { image: 'https://i.imgur.com/HK0hexr.jpg'},
  { image: 'https://i.imgur.com/B3nNhLZ.jpg'},
  { image: 'https://i.imgur.com/pXVzS6o.jpg'},
  { image: 'https://i.imgur.com/zOEa8PW.jpg'},
  { image: 'https://i.imgur.com/wjMA4qa.jpg'},
  { image: 'https://i.imgur.com/dIl7Itf.jpg'},
  { image: 'https://i.imgur.com/PXcyvHm.jpg'},
  { image: 'https://i.imgur.com/s9u2hXK.jpg'},
  { image: 'https://i.imgur.com/Fyxo5ON.jpg'},
  { image: 'https://i.imgur.com/Mf1JixN.jpg'},
  { image: 'https://i.imgur.com/Mdacm1F.jpg'},
  { image: 'https://i.imgur.com/ZChUUu0.jpg'},
  { image: 'https://i.imgur.com/noZfsDe.jpg'},
  { image: 'https://i.imgur.com/rJNxztU.jpg'},
  { image: 'https://i.imgur.com/xqGUpvh.jpg'},
  { image: 'https://i.imgur.com/7BRB3ff.jpg'},
  { image: 'https://i.imgur.com/hhLOl7b.jpg'},
  { image: 'https://i.imgur.com/CMs5amJ.jpg'},
  { image: 'https://i.imgur.com/LITg6KT.jpg'},
  { image: 'https://i.imgur.com/kAuPQze.jpg'},
  { image: 'https://i.imgur.com/QhNxtwI.jpg'},
  { image: 'https://i.imgur.com/BGuLtfY.jpg'},
  { image: 'https://i.imgur.com/xTPPcFc.jpg'},
  { image: 'https://i.imgur.com/CZfhctY.jpg'},
  { image: 'https://i.imgur.com/lXrGiKQ.jpg'},
  { image: 'https://i.imgur.com/s4sxMA9.jpg'},
  { image: 'https://i.imgur.com/ofWEjib.jpg'},
  { image: 'https://i.imgur.com/VfLj14v.jpg'},
  { image: 'https://i.imgur.com/Dgkt9lw.jpg'},
  { image: 'https://i.imgur.com/KutIQ4i.jpg'},
  { image: 'https://i.imgur.com/kdReYTw.jpg'},
  { image: 'https://i.imgur.com/7GgEwcv.jpg'},
  { image: 'https://i.imgur.com/gsDlpLe.jpg'},
  { image: 'https://i.imgur.com/gjtPef6.jpg'},
  { image: 'https://i.imgur.com/PsFprfe.jpg'},
  { image: 'https://i.imgur.com/h8PaZlu.jpg'},
  { image: 'https://i.imgur.com/uvTEmG4.jpg'},
  { image: 'https://i.imgur.com/8vCvDrL.jpg'},
  { image: 'https://i.imgur.com/GthUuOx.jpg'},
  { image: 'https://i.imgur.com/vCUWmO8.jpg'},
  { image: 'https://i.imgur.com/iuzcv92.jpg'},
  { image: 'https://i.imgur.com/PhmrzeR.jpg'},
  { image: 'https://i.imgur.com/5g5ON9w.jpg'},
  { image: 'https://i.imgur.com/eFpCOzc.jpg'},
  { image: 'https://i.imgur.com/LdFf0Fm.jpg'},
  { image: 'https://i.imgur.com/kGPENzh.jpg'},
  { image: 'https://i.imgur.com/Us0lcvF.jpg'},
  { image: 'https://i.imgur.com/K4zAeQz.jpg'},
  { image: 'https://i.imgur.com/VcT1Kel.jpg'},
  { image: 'https://i.imgur.com/k7p8xb6.jpg'},
  { image: 'https://i.imgur.com/2bhVxg5.jpg'},
  { image: 'https://i.imgur.com/H15c3qi.jpg'},
  { image: 'https://i.imgur.com/9oa8lMJ.jpg'},
  { image: 'https://i.imgur.com/SfClgKD.jpg'},
  { image: 'https://i.imgur.com/7wsvs9B.jpg'},
  { image: 'https://i.imgur.com/O9RLaS8.jpg'},
  { image: 'https://i.imgur.com/Jfeznh3.jpg'},
  { image: 'https://i.imgur.com/n7pw59c.jpg'},
  { image: 'https://i.imgur.com/hGlj2iB.jpg'},
  { image: 'https://i.imgur.com/I0Ep5j7.jpg'},
  { image: 'https://i.imgur.com/FTT5PRA.jpg'},
  { image: 'https://i.imgur.com/9QidApE.jpg'},
  { image: 'https://i.imgur.com/2OEWMpX.jpg'},
  { image: 'https://i.imgur.com/BWAw70W.jpg'},
  { image: 'https://i.imgur.com/7cZ9VPc.jpg'},
  { image: 'https://i.imgur.com/9OdR1u3.jpg'},
  { image: 'https://i.imgur.com/3c2rX3A.jpg'},
  { image: 'https://i.imgur.com/hQgVqXV.jpg'},
  { image: 'https://i.imgur.com/dXW85aD.jpg'},
  { image: 'https://i.imgur.com/ofPu10A.jpg'},
  { image: 'https://i.imgur.com/AC4ccS3.jpg'},
  { image: 'https://i.imgur.com/DfQpE5I.jpg'},
  { image: 'https://i.imgur.com/RJrjNv0.jpg'},
  { image: 'https://i.imgur.com/lBcZbmA.png'},
  { image: 'https://i.imgur.com/JWTw3PW.jpg'},
  { image: 'https://i.imgur.com/ZCEyBLG.jpg'}])

  #{ image: ''}

system "clear"  
  puts "After seeding the database: "
  puts " - There are #{User.count} Users."
  puts " - There are #{Task.count} Tasks."
  puts " - There are #{TaskImage.count} Task Images."
  puts " - There are #{Sticker.count} Stickers."
  puts ""